#!/usr/bin/env python3
"""Generate docs/index.md from the documentation directory tree."""

from __future__ import annotations

import argparse
from pathlib import Path
from urllib.parse import quote

SECTIONS = ("architecture", "decisions", "features", "proposals")


def display_name(path: Path) -> str:
    """Turn a file or directory name into a readable index label."""
    name = path.stem if path.is_file() else path.name
    return name.replace("-", " ").replace("_", " ").strip().title()


def markdown_link(path: Path, docs_dir: Path) -> str:
    relative_path = path.relative_to(docs_dir).as_posix()
    return f"[{display_name(path)}]({quote(relative_path, safe='/')})"


def directory_lines(directory: Path, docs_dir: Path, depth: int = 0) -> list[str]:
    """Return Markdown bullets for Markdown files and nested directories."""
    if not directory.is_dir() or directory.name.startswith("_"):
        return []

    indent = "  " * depth
    lines: list[str] = []

    entries = sorted(
        (
            entry
            for entry in directory.iterdir()
            if not entry.name.startswith("_")
            and (entry.is_dir() or entry.suffix.lower() == ".md")
        ),
        key=lambda entry: (entry.name.casefold(), entry.name),
    )

    for entry in entries:
        if entry.is_dir():
            children = directory_lines(entry, docs_dir, depth + 1)
            if children:
                lines.append(f"{indent}- {display_name(entry)}")
                lines.extend(children)
        else:
            lines.append(f"{indent}- {markdown_link(entry, docs_dir)}")

    return lines


def build_index(docs_dir: Path) -> str:
    lines = [
        "# Documentation Index",
        "",
        "<!-- Generated by generate_docs_index.py. Do not edit manually. -->",
        "",
    ]

    for section in SECTIONS:
        lines.append(f"## {section.title()}")
        entries = directory_lines(docs_dir / section, docs_dir)
        lines.extend(entries or ["No documents yet"])

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "docs_dir",
        nargs="?",
        type=Path,
        default=Path("docs"),
        help="documentation directory containing the four sections (default: docs)",
    )
    args = parser.parse_args()

    docs_dir = args.docs_dir.resolve()
    if not docs_dir.is_dir():
        parser.error(f"documentation directory does not exist: {docs_dir}")

    index_path = docs_dir / "index.md"
    index_path.write_text(build_index(docs_dir), encoding="utf-8")
    print(f"Generated {index_path}")


if __name__ == "__main__":
    main()
