//! Strict typed deserialization of `minegr.toml`.

use std::collections::BTreeMap;
use std::fs::{self, File};
use std::io::{self, Read};
use std::os::unix::fs::MetadataExt;
use std::path::Path;

use rustix::fs::{CWD, Mode, OFlags, openat};
use rustix::process::geteuid;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use thiserror::Error;

use crate::config_path::ConfigPath;

/// The only configuration format version supported by this release.
pub const CONFIG_VERSION: u32 = 1;

/// One Minegr instance configuration.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Config {
    /// Minegr-owned identity and format fields.
    pub minegr: MinegrConfig,
    /// Minecraft artifact coordinates and properties.
    pub minecraft: MinecraftConfig,
    /// Java executable and launch arguments.
    pub java: JavaConfig,
}

/// Minegr-owned configuration fields.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MinegrConfig {
    /// Configuration schema version.
    pub config_version: u32,
    /// Instance UUID generated by `minegr init`.
    pub uuid: Option<String>,
    /// Human-readable instance name.
    pub name: String,
}

/// Supported Minecraft server platforms.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Platform {
    /// Mojang's Vanilla server.
    Vanilla,
    /// PaperMC Paper.
    Paper,
    /// Fabric Loader.
    Fabric,
}

/// Minecraft artifact and generated-property configuration.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MinecraftConfig {
    /// Server platform.
    pub platform: Platform,
    /// Exact Minecraft version.
    pub version: String,
    /// Exact Paper build, when Paper is selected.
    pub build: Option<u64>,
    /// Exact Fabric loader version, when Fabric is selected.
    pub loader: Option<String>,
    /// Exact Fabric installer version, when Fabric is selected.
    pub installer: Option<String>,
    /// Published artifact checksum, when available.
    pub checksum: Option<String>,
    /// Whether the Minecraft EULA was explicitly accepted.
    pub eula: bool,
    /// Values written to `server.properties`.
    #[serde(default)]
    pub properties: BTreeMap<String, PropertyValue>,
}

/// A scalar value accepted in `[minecraft.properties]`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PropertyValue {
    /// A true or false property value.
    Boolean(bool),
    /// A signed integer property value.
    Integer(i64),
    /// A floating-point property value.
    Float(f64),
    /// A string property value.
    String(String),
}

/// Java process launch configuration.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JavaConfig {
    /// Configured Java executable, or `None` to discover it on PATH.
    pub executable: Option<String>,
    /// Arguments placed before Minegr's `-jar ./server.jar` arguments.
    pub jvm_args: Vec<String>,
    /// Arguments placed after `./server.jar`.
    pub server_args: Vec<String>,
}

/// A successfully loaded configuration and its filesystem metadata.
#[derive(Debug)]
pub struct LoadedConfig {
    /// Deserialized configuration.
    pub config: Config,
    /// Owner ID reported by the host filesystem.
    pub owner_uid: u32,
    /// Unix permission bits on the configuration file.
    pub mode: u32,
    /// Exact UTF-8 source read from the validated file descriptor.
    pub source: String,
    /// File identity against which any later atomic rewrite must be conditioned.
    pub identity: ConfigFileIdentity,
}

/// Stable identity of the exact configuration file that was loaded and validated.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ConfigFileIdentity {
    /// Owner ID reported by the opened file.
    pub owner_uid: u32,
    /// Filesystem device identity.
    pub device_id: u64,
    /// Filesystem inode identity.
    pub inode: u64,
    /// SHA-256 digest of exact bytes parsed from the loaded file.
    pub content_hash: [u8; 32],
}

/// Metadata used to prove that selection and reading refer to one safe file.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct LoadMetadata {
    /// Whether the entry is a regular file.
    pub regular: bool,
    /// Unix owner ID.
    pub owner_uid: u32,
    /// Unix permission and type bits.
    pub mode: u32,
    /// Filesystem device identity.
    pub device_id: u64,
    /// Filesystem inode identity.
    pub inode: u64,
}

/// Filesystem operations required by race-resistant configuration loading.
pub trait ConfigLoadOps {
    /// Readable configuration handle.
    type File: Read;

    /// Opens the canonical target without following a final symlink.
    fn open(&mut self, path: &Path) -> io::Result<Self::File>;
    /// Reads metadata from the already-open handle.
    fn metadata(&mut self, file: &Self::File) -> io::Result<LoadMetadata>;
    /// Inspects the user-selected entry without following its final symlink.
    fn inspect_selected(&mut self, path: &Path) -> io::Result<LoadMetadata>;
    /// Returns the effective user ID allowed to load configuration.
    fn current_uid(&self) -> u32;
}

/// A failure while loading a selected configuration file.
#[derive(Debug, Error)]
pub enum LoadConfigError {
    /// The selected path cannot be inspected.
    #[error("could not inspect file: {0}")]
    Inspect(#[source] io::Error),
    /// The selected path is not a regular file.
    #[error("selected path is not a regular file")]
    NotRegular,
    /// The file belongs to another operating-system user.
    #[error("file is owned by user {actual}, expected user {expected}")]
    ForeignOwner {
        /// Actual owner UID.
        actual: u32,
        /// Required owner UID.
        expected: u32,
    },
    /// The selected entry and opened canonical target no longer identify one file.
    #[error("configuration path changed while it was being loaded")]
    ChangedDuringLoad,
    /// The selected file cannot be read completely as UTF-8.
    #[error("could not read file: {0}")]
    Read(#[source] io::Error),
    /// TOML did not match the strict schema.
    #[error("invalid TOML: {0}")]
    Deserialize(#[from] toml::de::Error),
    /// The file uses a schema version unsupported by this binary.
    #[error("unsupported config_version {actual}; expected {expected}")]
    UnsupportedVersion {
        /// Version found in the file.
        actual: u32,
        /// Version supported by this binary.
        expected: u32,
    },
}

/// Loads one regular, current-user-owned UTF-8 configuration file.
pub fn load_config(path: &ConfigPath) -> Result<LoadedConfig, LoadConfigError> {
    load_config_with(&mut SystemConfigLoadOps, path)
}

/// Loads configuration through an injected filesystem boundary.
pub fn load_config_with<O: ConfigLoadOps>(
    operations: &mut O,
    path: &ConfigPath,
) -> Result<LoadedConfig, LoadConfigError> {
    let mut file = operations
        .open(path.as_path())
        .map_err(LoadConfigError::Read)?;
    let metadata = operations
        .metadata(&file)
        .map_err(LoadConfigError::Inspect)?;
    if !metadata.regular {
        return Err(LoadConfigError::NotRegular);
    }

    let expected_uid = operations.current_uid();
    if metadata.owner_uid != expected_uid {
        return Err(LoadConfigError::ForeignOwner {
            actual: metadata.owner_uid,
            expected: expected_uid,
        });
    }

    let selected = operations
        .inspect_selected(path.selected_path())
        .map_err(LoadConfigError::Inspect)?;
    if !selected.regular {
        return Err(LoadConfigError::NotRegular);
    }
    if selected.device_id != metadata.device_id || selected.inode != metadata.inode {
        return Err(LoadConfigError::ChangedDuringLoad);
    }

    let mut source = String::new();
    file.read_to_string(&mut source)
        .map_err(LoadConfigError::Read)?;
    let config: Config = toml::from_str(&source)?;
    if config.minegr.config_version != CONFIG_VERSION {
        return Err(LoadConfigError::UnsupportedVersion {
            actual: config.minegr.config_version,
            expected: CONFIG_VERSION,
        });
    }
    let content_hash = Sha256::digest(source.as_bytes()).into();

    Ok(LoadedConfig {
        config,
        owner_uid: metadata.owner_uid,
        mode: metadata.mode & 0o777,
        source,
        identity: ConfigFileIdentity {
            owner_uid: metadata.owner_uid,
            device_id: metadata.device_id,
            inode: metadata.inode,
            content_hash,
        },
    })
}

#[derive(Debug)]
struct SystemConfigLoadOps;

impl ConfigLoadOps for SystemConfigLoadOps {
    type File = File;

    fn open(&mut self, path: &Path) -> io::Result<Self::File> {
        let descriptor = openat(
            CWD,
            path,
            OFlags::RDONLY | OFlags::CLOEXEC | OFlags::NOFOLLOW,
            Mode::empty(),
        )?;
        Ok(File::from(descriptor))
    }

    fn metadata(&mut self, file: &Self::File) -> io::Result<LoadMetadata> {
        file.metadata().map(metadata_from)
    }

    fn inspect_selected(&mut self, path: &Path) -> io::Result<LoadMetadata> {
        fs::symlink_metadata(path).map(metadata_from)
    }

    fn current_uid(&self) -> u32 {
        geteuid().as_raw()
    }
}

fn metadata_from(metadata: fs::Metadata) -> LoadMetadata {
    LoadMetadata {
        regular: metadata.file_type().is_file(),
        owner_uid: metadata.uid(),
        mode: metadata.mode(),
        device_id: metadata.dev(),
        inode: metadata.ino(),
    }
}
